# Server port
server:
  port: 8899
# datasource
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/saas_book?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Amin6248
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Hikari Connection pool configuration
    hikari:
    # Minimum number of idle connections
     minimum-idle: 5
    # Maximum time for idle connections to survive, default 600,000 (10 minutes)     idle-timeout: 180000
     maximum-pool-size: 10
    # This property controls the default auto-commit behavior of connections returned from the pool, default value: true     auto-commit: true
    # connection pool name
     pool-name: MyHikariCP
    # This attribute controls the longest life cycle of the connection in the pool. A value of 0 indicates an infinite life cycle. The default is 1800000 is 30 min
     max-lifetime: 1800000
    # Database connection timeout, the default is 30 seconds, which is 30000
     connection-timeout: 30000
     connection-test-query: SELECT 1
# mvc web resources dir
  mvc:
    view:
      suffix: .html
      prefix: /templates/
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true
      fail_on_empty_beans: false
    time-zone: GMT+8
    #    default-property-inclusion: NON_EMPTY
    deserialization:
      fail_on_unknown_properties: false
  # servlet max size for fileUpload
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
# mybatis config
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
