# Server port
server:
  port: 8080
# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demoTest?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Amin6248
# mvc web resources dir
  mvc:
    view:
      suffix: .html
      prefix: /templates/
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
# mybatis config
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
